### ISSUE TITLE
How to develop?

### ISSUE THREAD

**Issue by sebadamus** [akaunting/docs#1]
Kind of large question :-p, I had worked with php, and phpmaker as frontend creator.  Have never worked with laravel.  Do you have any easy hint/doc about how to start for a newbie with this framework?

Thanks!

**Comment by denisdulici** [comment]
I would advise the following resources to start with Laravel:
https://laravel.com/docs/5.4
https://laracasts.com/series/laravel-from-scratch-2017

Plz, use the forum for further help https://akaunting.com/forum/category/development
