### ISSUE TITLE
I cannot change item's price

### ISSUE THREAD

**Issue by cozkur** [akaunting/docs#9]
I am using the Turkish version and only Turkish currency. I have created a bunch of items to sell. Later I wanted to modify the price, and was unable to. For instance, I change the price from 7,00 TL to 7,50, I press "Save" but when I open it again I see no change, it still shows 7,00 TL. The same thing happens to every item in the list. It maintains the price I set when I create the item, and impossible to change the price later.

**Comment by denisdulici** [comment]
Plz, use the forum for support https://akaunting.com/forum
